Repository vaish1707/cloudfunctions, pull requests merged in 2020-10, with the labels that each got.

#5 New route
  functions/controllers/index.js
  functions/index.js
Labels: hacktoberfest

#6 Add message
  functions/controllers/index.js
  functions/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#7 adding functionality to upload in the url form
  functions/controllers/index.js
Labels: hacktoberfest-accepted.

#8 Date.now() to UTC time
  functions/controllers/index.js
Labels: hacktoberfest-accepted

#9 adding file limit to body-parser
  functions/index.js
Labels: hacktoberfest-accepted
